// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7rDMbEPrHLQF2DAq3RNBPVqppcXbVIhQ',
    appId: '1:152779337859:web:b8bc6b946f22560f886bb6',
    messagingSenderId: '152779337859',
    projectId: 'tfg-flixscore',
    authDomain: 'tfg-flixscore.firebaseapp.com',
    storageBucket: 'tfg-flixscore.firebasestorage.app',
    measurementId: 'G-TLMJKPR9Y9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMI1-Ce505v2LctsA_SagW74_OXT99TmY',
    appId: '1:152779337859:android:a3b871c45dba44ff886bb6',
    messagingSenderId: '152779337859',
    projectId: 'tfg-flixscore',
    storageBucket: 'tfg-flixscore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEpXW10DNu-FYTFJkNDZCkqxB_a8p1P_Y',
    appId: '1:152779337859:ios:f8b3d9a4b2d4da42886bb6',
    messagingSenderId: '152779337859',
    projectId: 'tfg-flixscore',
    storageBucket: 'tfg-flixscore.firebasestorage.app',
    iosClientId: '152779337859-7po3pqg41e8sqo195mks74ivc31a2328.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontFlixscore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEpXW10DNu-FYTFJkNDZCkqxB_a8p1P_Y',
    appId: '1:152779337859:ios:f8b3d9a4b2d4da42886bb6',
    messagingSenderId: '152779337859',
    projectId: 'tfg-flixscore',
    storageBucket: 'tfg-flixscore.firebasestorage.app',
    iosClientId: '152779337859-7po3pqg41e8sqo195mks74ivc31a2328.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontFlixscore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7rDMbEPrHLQF2DAq3RNBPVqppcXbVIhQ',
    appId: '1:152779337859:web:ba9e4240cd7c5135886bb6',
    messagingSenderId: '152779337859',
    projectId: 'tfg-flixscore',
    authDomain: 'tfg-flixscore.firebaseapp.com',
    storageBucket: 'tfg-flixscore.firebasestorage.app',
    measurementId: 'G-K30V7D9D1K',
  );

}